In [1]:
from multi_label_cwru import MultiLabelSplitter

**Define root path and output path**

In [8]:
cwru_root = r"D:\Project\Bearing\dataset\CWRU"
output_path = r"D:\Project\Bearing\dataset\multi_label_cwru"

**Initialize splitter**

In [9]:
splitter = MultiLabelSplitter(cwru_root)

**Create output directory**

In [16]:
splitter.create_folders(output_path)

**Split to train and test**

In [17]:
train, test = splitter.filtering()

Total files: 66

Split Recipe
------------------------------
DE-IR -> 021
DE-OR -> 007
DE-B -> 007
FE-IR -> 021
FE-OR -> 014
FE-B -> 007

Dataset Summary
------------------------------
Train: 45
Test : 21

**Inspect train and test set**

In [18]:
train.head()

,path,label,type,severity,location
0,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,014,DE
1,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,014,DE
2,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,014,DE
3,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,014,DE
4,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,021,DE

In [19]:
test.head()

,path,label,type,severity,location
0,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,007,DE
1,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,007,DE
2,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,007,DE
3,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[0, 0, 1]",B,007,DE
4,D:\Project\Bearing\dataset\CWRU\12k_Drive_End_...,"[1, 0, 0]",IR,021,DE

**Splitting**

In [20]:
splitter.splitting(output_path, train, train=True)
splitter.splitting(output_path, test, train=False)

**Move to new directory**

In [21]:
splitter.move_normal(output_path)